version: '3.9'

services:
  db:
    image: mysql:8
    container_name: cafeapp-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cafeapp
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./cafeapp
    container_name: cafeapp-backend
    ports:
      - "8081:8081"
    environment:
    
    depends_on:
      - db

  frontend:
    build: ./cafeapp-frontend
    container_name: cafeapp-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
