version: '3.9'
services:
  backend:
    build: ./cafeapp
    container_name: cafeapp-backend
    ports:
      - "8081:8080"

  frontend:
    build: ./cafeapp-frontend
    container_name: cafeapp-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
