version: "3.8"

services:
  db:
    image: mysql:8
    container_name: cafeapp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cafeapp
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: caoleson04/my-backend:latest
    container_name: cafeapp-backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      # Thêm biến môi trường nếu backend cần
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: cafeapp
    depends_on:
      - db

  frontend:
    image: caoleson04/my-frontend:latest
    container_name: cafeapp-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
