version: '3.9'

services:
  db:
    image: mysql:8
    container_name: cafeapp-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cafeapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./cafeapp
    container_name: cafeapp-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cafeapp
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  frontend:
    build: ./cafeapp-frontend
    container_name: cafeapp-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
  