services:
  db:
    image: mysql:8
    container_name: cafeapp-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cafeapp
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"  # đổi port host để tránh xung đột với MySQL trên Windows
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: caoleson04/my-backend:latest
    container_name: cafeapp-backend
    ports:
      - "8081:8081"
    depends_on:
      - db

  frontend:
    image: caoleson04/my-frontend:latest
    container_name: cafeapp-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
